Update documentation for Calico operator
awsdocs/amazon-eks-user-guide pull request #341
Opened 2021-03-24 18:06 UTC by caseydavenport

*Issue #, if available:*

*Description of changes:*

This is a documentation PR that corresponds with the following changes:

- Switch Calico to operator: https://github.com/aws/amazon-vpc-cni-k8s/pull/1297 
- Fix Calico installation issue: https://github.com/aws/amazon-vpc-cni-k8s/pull/1410

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-24 18:12 UTC, tmjd requested changes
One change needed but otherwise LGTM.

2021-03-24 18:12 UTC, tmjd commented on doc_source/calico.md
> +        curl -o calico-crs.yaml https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.5/config/v1.7/calico-operator.yaml
I think this was suppose to be calico-crs.yaml.

2021-03-29 14:45 UTC, jimdial-aws commented
I get 404 errors for all the new links in this PR.

2021-03-29 16:57 UTC, caseydavenport commented
> I get 404 errors for all the new links in this PR.

@jimdial-aws Yeah, I'm not sure how to order these, so would appreciate guidance on what the right process is. This PR depends on the changes in this one: https://github.com/aws/amazon-vpc-cni-k8s/pull/1410

I think the links probably need to be updated for the next release (v1.8?). The changes in that PR (1410) are against master.

2021-03-29 17:33 UTC, jimdial-aws commented
@caseydavenport  Once the other PR changes are merged and these links are live, I'll look at merging this again.  Thanks.

2021-04-02 17:39 UTC, jayanthvn commented
I have merged this aws/amazon-vpc-cni-k8s#1410 to master.

2021-04-02 17:58 UTC, caseydavenport commented
Thanks @jayanthvn! 

Is there a way to make this docs update in such a way that it will go live with the next release from master (v1.8)?

2021-04-02 19:10 UTC, jimdial-aws commented
I'll watch for the change to go live and try to make the docs change as soon as possible, but it may not be until Monday, depending on when the change goes live.

2021-04-02 21:02 UTC, merged

2021-04-02 21:02 UTC, jimdial-aws commented
Thank you for your submission!